// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Buyers
    {
        public Buyers()
        {
            Shopcarts = new HashSet<Shopcarts>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int Phonenumber { get; set; }
        public string Email { get; set; }
        public string Region { get; set; }
        public string City { get; set; }

        public virtual ICollection<Shopcarts> Shopcarts { get; set; }
    }
}