// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Categories
    {
        public Categories()
        {
            Products = new HashSet<Products>();
            Subcategories = new HashSet<Subcategories>();
        }

        public int Id { get; set; }
        public int SectionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }

        public virtual Sections Section { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Subcategories> Subcategories { get; set; }
    }
}