// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Category
    {
        public Category()
        {
            Products = new HashSet<Product>();
            Subcategories = new HashSet<Subcategory>();
        }

        public int Id { get; set; }
        public int SectionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }

        public virtual Section Section { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Subcategory> Subcategories { get; set; }
    }
}