// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class OrdersLogin
    {
        public int Id { get; set; }
        public string ShopcartId { get; set; }
        public decimal? TotalPrice { get; set; }
        public DateTime? ScheduledDate { get; set; }

        public virtual ShopcartItems Shopcart { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
    }
}