// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class OrdersNoLogin
    {
        public int Id { get; set; }
        public string ShopcartId { get; set; }
        public decimal? TotalPrice { get; set; }
        public DateTime? ScheduledDate { get; set; }
        public string BuyerName { get; set; }
        public string BuyerSurname { get; set; }
        public string BuyerPatronymic { get; set; }
        public string Region { get; set; }
        public string City { get; set; }

        public virtual ShopcartItemsNoLogin Shopcart { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}