// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class ProductDescription
    {
        public int ProductId { get; set; }
        public int DescriptionTitleId { get; set; }
        public string DescriptionText { get; set; }

        public virtual SubcategoryDescriptionTitle DescriptionTitle { get; set; }
        public virtual Products Product { get; set; }
    }
}