// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Product
    {
        public Product()
        {
            ProductDescriptions = new HashSet<ProductDescription>();
            ShopcartItems = new HashSet<ShopcartItem>();
            ShopcartItemsNoLogins = new HashSet<ShopcartItemsNoLogin>();
        }

        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int? SubcategoryId { get; set; }
        public int ManufacturerId { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int? Amount { get; set; }
        public string ImagePath { get; set; }
        public bool? IsVisible { get; set; }

        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        public virtual ICollection<ProductDescription> ProductDescriptions { get; set; }
        public virtual ICollection<ShopcartItem> ShopcartItems { get; set; }
        public virtual ICollection<ShopcartItemsNoLogin> ShopcartItemsNoLogins { get; set; }
    }
}