// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Products
    {
        public Products()
        {
            ShopcartItems = new HashSet<ShopcartItems>();
            ShopcartItemsNoLogin = new HashSet<ShopcartItemsNoLogin>();
        }

        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int? SubcategoryId { get; set; }
        public int ManufacturerId { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int? Amount { get; set; }
        public string ImagePath { get; set; }
        public bool? IsVisible { get; set; }

        public virtual Categories Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Subcategories Subcategory { get; set; }
        public virtual ICollection<ShopcartItems> ShopcartItems { get; set; }
        public virtual ICollection<ShopcartItemsNoLogin> ShopcartItemsNoLogin { get; set; }
    }
}