// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Shopcarts
    {
        public string Id { get; set; }
        public string BuyerId { get; set; }

        public virtual Buyers Buyer { get; set; }
        public virtual ShopcartItems ShopcartItems { get; set; }
    }
}