// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Shopcart
    {
        public string Id { get; set; }
        public string BuyerId { get; set; }

        public virtual Buyer Buyer { get; set; }
        public virtual ShopcartItem ShopcartItem { get; set; }
    }
}