// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class ShopcartsNoLogin
    {
        public string Id { get; set; }

        public virtual ShopcartItemsNoLogin ShopcartItemsNoLogin { get; set; }
    }
}