// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class ShopcartItemsNoLogin
    {
        public ShopcartItemsNoLogin()
        {
            OrdersNoLogin = new HashSet<OrdersNoLogin>();
        }

        public string ShopcartId { get; set; }
        public int ProductId { get; set; }
        public int? Quality { get; set; }

        public virtual Products Product { get; set; }
        public virtual ShopcartsNoLogin Shopcart { get; set; }
        public virtual ICollection<OrdersNoLogin> OrdersNoLogin { get; set; }
    }
}