// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class SubcategoryDescriptionTitle
    {
        public int Id { get; set; }
        public int SubcategoryId { get; set; }
        public string Title { get; set; }

        public virtual Subcategories Subcategory { get; set; }
    }
}