// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ApplicationCore.Entities
{
    public partial class Subcategory
    {
        public Subcategory()
        {
            Products = new HashSet<Product>();
            SubcategoryDescriptionTitles = new HashSet<SubcategoryDescriptionTitle>();
        }

        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<SubcategoryDescriptionTitle> SubcategoryDescriptionTitles { get; set; }
    }
}